### ISSUE TITLE
Collections API: Update to 2.0

### ISSUE THREAD

**Issue by marczych** [iFixit/ifixit-microsoft#10]
This app still uses the [0.1 collections API endpoint](https://github.com/iFixit/ifixit-microsoft/blob/497cf412d933cd01101f2badbd8cf8099c3ff5cb/iFixit.Domain/Services/V2_0/ServiceBroker.cs#L25) which will be deprecated soon. It needs to be updated to use the [2.0 collections API](https://www.ifixit.com/api/2.0/collections) to avoid a disruption of service when the 0.1 API is deprecated.

**Comment by cmorgado** [comment]
Source code updated, contact me for xap and appx to update store

**Comment by marczych** [comment]
Fixed with 2dba3f265661a887f42f0d8d79065eff796db434. Thanks for the quick response!

**Comment by MutantFreak** [comment]
@Diakonia7 will be in touch soon to get the updated app deployed!
