### ISSUE TITLE
Add support for windows 10 desktops

### ISSUE THREAD

**Issue by Samuel12321** [iFixit/ifixit-microsoft#13]
The app is only availible for windows mobile devices. It would be nice if windows 10 desktop support was added.
![annotation](https://user-images.githubusercontent.com/35312698/48116919-66297980-e2cc-11e8-9bb2-ae66a8f48e7c.png)

**Comment by kwiens** [comment]
Thanks for the feature request. We don't have any plans to do that right now, but we'll keep it in mind for the future of the app.

But to be honest, right now we're spending more of our time focusing on the web experience of iFixit than this app. If the community wants to step up and maintain it, we're happy to assist!
