### ISSUE TITLE
Customize User-Agent

### ISSUE THREAD

**Issue by xiongchiamiov** [iFixit/ifixit-microsoft#4]
Based on server logs, it looks like the user-agent for this app is set to "NativeHost".  It would be nice to have this changed to something more indicative of what it is.

[This question](http://stackoverflow.com/q/13306090/120999) on StackOverflow may be helpful, although I think [this documentation](http://msdn.microsoft.com/en-us/library/system.net.httpwebrequest.useragent.aspx) is actually more relevant, if I remember your code correctly.

The iOS app uses a user-agent of "iFixit 39 rv:1.3".  The Android app uses "iFixitAndroid/20".  Something along those lines would be good - an indication of what the app is for (iFixit), the platform, and a version number.

In iOS, when you assign the user-agent, the OS automatically adds device information (so the header is actually `User-Agent: iFixit 39 rv:1.3 (iPod touch; iPhone OS 6.1.2; en_US)` or similar); in Android, the OS does not.  You should check to see what Windows Phone does, and add the device information manually if necessary - it's enormously helpful to have when diagnosing issues.

Thanks!

**Comment by kwiens** [comment]
Can we do the windows version user agent differentiation for the upcoming app release with the new api? That would be great!

**Comment by cmorgado** [comment]
Yes we can, please just define it I'll do it

**Comment by cmorgado** [comment]
We need to submit to store this new edited code

**Comment by marczych** [comment]
> We need to submit to store this new edited code

Great, thanks!
