### ISSUE TITLE
W8 App Issues for Launch

### ISSUE THREAD

**Issue by MutantFreak** [iFixit/ifixit-microsoft#7]
Priorities are listed with each item. 1 is highest priority, 10 is lowest priority.
I reserved 1 for tasks which are bugs or things that absolutely need to be implemented before launch.

Check the boxes as they are completed:

**Issues from MS Team**
--------------------

**Design Issues**
--------------------
- [ ] 1 It should never show the camera + ? image when there is an image. Right now it shows the camera + ? image before every loading image.
This behavior is the same on WindowsPhone, changing this requires changing a LOT of code ... its more than a day of work...

**Login**
---------------------

**Front Page**
---------------------

**Search results**
---------------------

**Guide View**
------------------------

- [ ] 2 On video steps, playing the video should play it in place, rather than opening it full screen. There should be a full-screen button on the bottom right of the video that opens it full-screen. 

**Introduction, Parts & Tools**
------------------------

**Breadcrumbs on Category View & Device View**
---------------------
- [x] 3 On category pages, breadcrumbs flicker and show the previous category breadcrubs you loaded. (E.G. Mac -> Laptop, even though you loaded Mac -> Laptop -> Macbook Pro. Once you reach a specific device, it flickers the breadcrumbs from the previous device you viewed.

**Device View (no children categories)**
---------------------

**Category View (has children categories)**
---------------------

- [x] 3 Truncated link under the Troubleshooting header - we should wrap long links onto multiple lines. (Ex category: Macbook Pro 13" Unibody 2010) (THIS is a problem with hyperlinks in W8 SDK within the richtext control , no solution found yet)

**Comment by kwiens** [comment]
What's the current status on this?

**Comment by MutantFreak** [comment]
The app has survived just fine since launch in its current state. Closing.
